---
- name: Install Go with Script
  hosts: 46.101.73.58,46.101.76.116
  become: true
  tasks:
    - name: Download install_script.sh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Ritvik32/Sample_ansible_playbook/main/install_script.sh
        dest: /root

    - name: Run install_script.sh
      ansible.builtin.shell:
        cmd: bash /root/install_script.sh



       
