---
- name: Install Go with Script
  hosts: 165.22.125.93,139.59.166.73
  become: true

  tasks:
    - name: Download install_script.sh
      get_url:
        url: "https://raw.githubusercontent.com/Ritvik32/Sample_ansible_playbook/main/install_script.sh"
        dest: /root
        mode: "755"

    - name: Run install_script.sh
      command: bash /root/install_script.sh
