---
- name: Install Go with Script
  hosts: 147.182.247.179,143.198.103.241
  become: true

  tasks:
    - name: Download install_script.sh
      get_url:
        url: "https://raw.githubusercontent.com/Ritvik32/Sample_ansible_playbook/main/install_script.sh"
        dest: /root
        mode: "755"

    - name: Run install_script.sh
      command: sh /root/install_script.sh
